openapi: 3.0.0
info:
  title: API de Im치genes
  description: API para gestionar registros de im치genes.
  version: 1.0.0

servers:
  - url: http://localhost:8002
    description: Servidor de desarrollo

paths:
  /images:
    get:
      summary: Obtener todas las im치genes
      responses:
        "200":
          description: Un arreglo JSON de im치genes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    url:
                      type: string
    post:
      summary: Crear una nueva imagen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                url:
                  type: string
      responses:
        "200":
          description: Imagen creada exitosamente

  /image/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
    get:
      summary: Obtener una imagen por ID
      responses:
        "200":
          description: Un objeto de imagen
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
                  url:
                    type: string
        "404":
          description: Imagen no encontrada
    put:
      summary: Actualizar una imagen por ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                url:
                  type: string
      responses:
        "200":
          description: Imagen actualizada exitosamente
        "404":
          description: Imagen no encontrada
    delete:
      summary: Eliminar una imagen por ID
      responses:
        "200":
          description: Imagen eliminada exitosamente
        "404":
          description: Imagen no encontrada
